
// This file has been generated by the GUI designer. Do not modify.
namespace DB2FAtest_gtk
{
	public partial class TwoFactorVerifyWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label codeLabel;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry codeEntry;

		private global::Gtk.Button verifyButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DB2FAtest_gtk.TwoFactorVerifyWindow
			this.Name = "DB2FAtest_gtk.TwoFactorVerifyWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("TwoFactorVerifyWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DB2FAtest_gtk.TwoFactorVerifyWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.codeLabel = new global::Gtk.Label();
			this.codeLabel.Name = "codeLabel";
			this.codeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Enter code generated by Google Authenticator");
			this.vbox2.Add(this.codeLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.codeLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.codeEntry = new global::Gtk.Entry();
			this.codeEntry.CanFocus = true;
			this.codeEntry.Name = "codeEntry";
			this.codeEntry.IsEditable = true;
			this.codeEntry.InvisibleChar = '●';
			this.hbox1.Add(this.codeEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.codeEntry]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.verifyButton = new global::Gtk.Button();
			this.verifyButton.CanFocus = true;
			this.verifyButton.Name = "verifyButton";
			this.verifyButton.UseUnderline = true;
			this.verifyButton.Label = global::Mono.Unix.Catalog.GetString("Verify");
			this.hbox1.Add(this.verifyButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.verifyButton]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.verifyButton.Clicked += new global::System.EventHandler(this.OnVerifyButtonClicked);
		}
	}
}
